const zoneGroups = [
	[	'zg_laNoscea',
		'limsaLominsa',
		'middleLaNoscea',
		'lowerLaNoscea',
		'easternLaNoscea',
		'westernLaNoscea',
		'upperLaNoscea',
		'outerLaNoscea',
		'mist',
		'wolvesDenPier'],
	[	'zg_shroud',
		'gridania',
		'centralShroud',
		'eastShroud',
		'southShroud',
		'northShroud',
		'theLavenderBeds'],
	[	'zg_thanalan',
		'uldah',
		'centralThanalan',
		'easternThanalan',
		'westernThanalan',
		'southernThanalan',
		'northernThanalan',
		'theGoblet'],
	[	'zg_ishgard',
		'ishgard',
		'coerthasCentralHighlands',
		'coerthasWesternHighlands',
		'theDravanianForelands',
		'theDravanianHinterlands',
		'idyllshire',
		'theChurningMists',
		'theSeaOfClouds',
		'azysLla'],
	[	'zg_gyrAbania',
		'rhalgrsReach',
		'theFringes',
		'thePeaks',
		'theLochs'],
	[	'zg_theEast',
		'kugane',
		'theRubySea',
		'yanxia',
		'theAzimSteppe',
		'shirogane'],
	[	'zg_eureka',
		'eurekaAnemos',
		'eurekaPagos',
		'eurekaPyros',
		'eurekaHydatos'],
	[	'zg_norvrandt',
		'theCrystarium',
		'lakeland',
		'eulmore',
		'kholusia',
		'amhAraeng',
		'ilMheg',
		'theRaktikaGreatwood',
		'theTempest'],
	[	'zg_other',
		'morDhona',
		'bozjanSouthernFront',
		'theDiadem'],
];

const translateZones = {
	jp: {
		zg_laNoscea : 'ラノシア',
		zg_shroud : '黒衣森',
		zg_thanalan : 'ザナラーン',
		zg_ishgard : 'イシュガルド周辺地域',
		zg_gyrAbania : 'ギラバニア',
		zg_theEast : '東方地域',
		zg_eureka : 'エウレカ',
		zg_norvrandt : 'ノルヴラント',
		zg_other : 'その他',
	limsaLominsa :	'リムサ・ロミンサ',
	middleLaNoscea :	'中央ラノシア',
	lowerLaNoscea :	'低地ラノシア',
	easternLaNoscea :	'東ラノシア',
	westernLaNoscea :	'西ラノシア',
	upperLaNoscea :	'高地ラノシア',
	outerLaNoscea :	'外地ラノシア',
	mist :	'ミスト・ヴィレッジ',
	wolvesDenPier :	'ウルヴズジェイル係船場',
	gridania :	'グリダニア',
	centralShroud :	'黒衣森：中央森林',
	eastShroud :	'黒衣森：東部森林',
	southShroud :	'黒衣森：南部森林',
	northShroud :	'黒衣森：北部森林',
	theLavenderBeds :	'ラベンダーベッド',
	uldah :	'ウルダハ',
	centralThanalan :	'中央ザナラーン',
	easternThanalan :	'東ザナラーン',
	westernThanalan :	'西ザナラーン',
	southernThanalan :	'南ザナラーン',
	northernThanalan :	'北ザナラーン',
	theGoblet :	'ゴブレットビュート',
	ishgard :	'イシュガルド',
	coerthasCentralHighlands :	'クルザス中央高地',
	coerthasWesternHighlands :	'クルザス西部高地',
	theDravanianForelands :	'高地ドラヴァニア',
	theDravanianHinterlands :	'低地ドラヴァニア',
	idyllshire :	'イデルシャイア',
	theChurningMists :	'ドラヴァニア雲海',
	theSeaOfClouds :	'アバラシア雲海',
	azysLla :	'アジス・ラー',
	rhalgrsReach :	'ラールガーズリーチ',
	theFringes :	'ギラバニア辺境地帯',
	thePeaks :	'ギラバニア山岳地帯',
	theLochs :	'ギラバニア湖畔地帯',
	kugane :	'クガネ',
	theRubySea :	'紅玉海',
	yanxia :	'ヤンサ',
	theAzimSteppe :	'アジムステップ',
	shirogane :	'シロガネ',
	eurekaAnemos :	'エウレカ：アネモス帯',
	eurekaPagos :	'エウレカ：パゴス帯',
	eurekaPyros :	'エウレカ：ピューロス帯',
	eurekaHydatos :	'エウレカ：ヒュダトス帯',
	theCrystarium :	'クリスタリウム',
	lakeland :	'レイクランド',
	eulmore :	'ユールモア',
	kholusia :	'コルシア島',
	amhAraeng :	'アム・アレーン',
	ilMheg :	'妖精郷イル・メグ',
	theRaktikaGreatwood :	'ラケティカ大森林',
	theTempest :	'テンペスト',
	morDhona :	'モードゥナ',
	bozjanSouthernFront :	'南方ボズヤ戦線',
	theDiadem :	'ディアデム諸島',
	}
}
